# Dependencies
highlighter:      rouge
gems: [jekyll-paginate, jekyll-gist, jekyll-github-metadata]

# Permalinks
permalink:        pretty

# Setup
title:            Ihor Havryliuk
tagline:          'An Android blog'
description:      'A blog on Android development and other trains of thoughts.<br>Made by <a href="https://twitter.com/IgorGavryliuk" target="_blank">@IgorGavryliuk</a>.'
url:              http://graviton57.github.io
baseurl:          /

author:
  name:           'Ihor Havryliuk'
  url:            https://twitter.com/IgorGavryliuk

paginate:         5

# Custom vars
github_link:	  https://github.com/graviton57

# GitHub Metadata setup
repository: 	  graviton57/graviton57.github.io

# Disqus comments configuration (leave blank to disable comments)
disqus_shortname: 'igorgavrilyuk'